import 'package:country_list/country_list.dart';

class NewsSettings {
  List<String> cities;
  List<String> countries;
  List<String> interests;
  bool wantsCities;
  bool wantsCountries;
  bool wantsInterests;
  String locale;
  String userPrompt;

  // Predefined lists
  List<String> predefinedCities = [
    "Abidjan (Côte d'Ivoire)",
    "Abobo (Côte d'Ivoire)",
    "Abomey-Calavi (Benin)",
    "Abu Dhabi (United Arab Emirates)",
    "Abéché (Chad)",
    "Accra (Ghana)",
    "Addis Ababa (Ethiopia)",
    "Aden (Yemen)",
    "Aktobe (Kazakhstan)",
    "Al Aḩmadī (Kuwait)",
    "Al Başrah al Qadīmah (Iraq)",
    "Al Mawşil al Jadīdah (Iraq)",
    "Al Muharraq (Bahrain)",
    "Al Ḩudaydah (Yemen)",
    "Alapi Village (Tuvalu)",
    "Aleppo (Syrian Arab Republic)",
    "Alexandria (Egypt)",
    "Algiers (Algeria)",
    "Ali Sabih (Djibouti)",
    "All Saints (Antigua and Barbuda)",
    "Almas (Sao Tome and Principe)",
    "Almaty (Kazakhstan)",
    "Alo (Wallis and Futuna Islands)",
    "Alofi (Niue)",
    "Amadora (Portugal)",
    "Amman (Jordan)",
    "Amsterdam (Netherlands)",
    "Andorra la Vella (Andorra)",
    "Ankara (Turkey)",
    "Anse Boileau (Seychelles)",
    "Antananarivo (Madagascar)",
    "Antofagasta (Chile)",
    "Antsirabe (Madagascar)",
    "Antwerpen (Belgium)",
    "Apia (Samoa)",
    "Ar Rayyān (Qatar)",
    "Ar Rifā‘ (Bahrain)",
    "Arawa (Papua New Guinea)",
    "Arequipa (Peru)",
    "Arijejen (Nauru)",
    "Arno (Marshall Islands)",
    "Arusha (Tanzania, United Republic of)",
    "As Sālimīyah (Kuwait)",
    "Asau (Samoa)",
    "Ashgabat (Turkmenistan)",
    "Asmara (Eritrea)",
    "Asunción (Paraguay)",
    "Atafu Village (Tokelau)",
    "Athens (Greece)",
    "Auckland (New Zealand)",
    "Auki (Solomon Islands)",
    "Avarua (Cook Islands)",
    "Bafatá (Guinea-Bissau)",
    "Baghdad (Iraq)",
    "Baie-Mahault (Guadeloupe)",
    "Baku (Azerbaijan)",
    "Bamako (Mali)",
    "Bamenda (Cameroon)",
    "Bandar Seri Begawan (Brunei Darussalam)",
    "Bangkok (Thailand)",
    "Bangui (Central African Republic)",
    "Banja Luka (Bosnia and Herzegovina)",
    "Barcelona (Spain)",
    "Basel (Switzerland)",
    "Basseterre (Saint Kitts and Nevis)",
    "Bata (Equatorial Guinea)",
    "Batumi (Georgia)",
    "Bawshar (Oman)",
    "Bayamón (Puerto Rico)",
    "Beau Bassin-Rose Hill (Mauritius)",
    "Beijing (China)",
    "Beirut (Lebanon)",
    "Bekasi (Indonesia)",
    "Belgrade (Serbia)",
    "Belize City (Belize)",
    "Belo Horizonte (Brazil)",
    "Bengaluru (India)",
    "Benghazi (Libyan Arab Jamahiriya)",
    "Bergen (Norway)",
    "Berlin (Germany)",
    "Betio Village (Kiribati)",
    "Bharatpur (Nepal)",
    "Big Bend (Swaziland)",
    "Bikenibeu Village (Kiribati)",
    "Bimbo (Central African Republic)",
    "Birkirkara (Malta)",
    "Birmingham (United Kingdom)",
    "Bisee (Saint Lucia)",
    "Bishkek (Kyrgyzstan)",
    "Bissau (Guinea-Bissau)",
    "Blantyre (Malawi)",
    "Blowing Point Village (Anguilla)",
    "Bo (Sierra Leone)",
    "Bobo-Dioulasso (Burkina Faso)",
    "Bodden Town (Cayman Islands)",
    "Bogotá (Colombia)",
    "Borama (Somalia)",
    "Borgo Maggiore (San Marino)",
    "Bouaké (Côte d'Ivoire)",
    "Boujdour (Western Sahara)",
    "Brades (Montserrat)",
    "Bratislava (Slovakia)",
    "Brazzaville (Congo)",
    "Bridgetown (Barbados)",
    "Brikama (Gambia)",
    "Brisbane (Australia)",
    "Brno (Czech Republic)",
    "Brokopondo (Suriname)",
    "Brooklyn (United States)",
    "Brussels (Belgium)",
    "Buchanan (Liberia)",
    "Bucharest (Romania)",
    "Budapest (Hungary)",
    "Buenos Aires (Argentina)",
    "Bujumbura (Burundi)",
    "Bulawayo (Zimbabwe)",
    "Bununka Kunda (Gambia)",
    "Bursa (Turkey)",
    "Busan (Korea, Republic of)",
    "Butare (Rwanda)",
    "Byera Village (Saint Vincent and the Grenadines)",
    "Bégoua (Central African Republic)",
    "Bălţi (Moldova, Republic of)",
    "Cairo (Egypt)",
    "Calgary (Canada)",
    "Cali (Colombia)",
    "Callao (Peru)",
    "Camagüey (Cuba)",
    "Camayenne (Guinea)",
    "Cape Town (South Africa)",
    "Caracas (Venezuela, Bolivarian Rep. of)",
    "Carolina (Puerto Rico)",
    "Carrefour (Haiti)",
    "Casablanca (Morocco)",
    "Castel (Guernsey)",
    "Castries (Saint Lucia)",
    "Cayenne (French Guiana)",
    "Chaguanas (Trinidad and Tobago)",
    "Charlotte Amalie (Virgin Islands (US))",
    "Chattogram (Bangladesh)",
    "Chisinau (Moldova, Republic of)",
    "Chitungwiza (Zimbabwe)",
    "Christchurch (New Zealand)",
    "Ciudad del Este (Paraguay)",
    "Cochabamba (Bolivia)",
    "Cockburn Town (Turks and Caicos Islands)",
    "Colombo (Sri Lanka)",
    "Conakry (Guinea)",
    "Constantine (Algeria)",
    "Copenhagen (Denmark)",
    "Cork (Ireland)",
    "Cotonou (Benin)",
    "Cruz Bay (Virgin Islands (US))",
    "Cuenca (Ecuador)",
    "Córdoba (Argentina)",
    "Da Nang (Viet Nam)",
    "Dakar (Senegal)",
    "Dakhla (Western Sahara)",
    "Damascus (Syrian Arab Republic)",
    "Dar es Salaam (Tanzania, United Republic of)",
    "Darhan (Mongolia)",
    "Daugavpils (Latvia)",
    "Davao (Philippines)",
    "Daşoguz (Turkmenistan)",
    "Debrecen (Hungary)",
    "Dededo Village (Guam)",
    "Dehiwala-Mount Lavinia (Sri Lanka)",
    "Delhi (India)",
    "Delmas 73 (Haiti)",
    "Denigomodu (Nauru)",
    "Dhaka (Bangladesh)",
    "Dikhil (Djibouti)",
    "Dili (Timor-Leste)",
    "Djibouti (Djibouti)",
    "Doha (Qatar)",
    "Dolisie (Congo)",
    "Douala (Cameroon)",
    "Douglas (Isle of Man)",
    "Dubai (United Arab Emirates)",
    "Dublin (Ireland)",
    "Dudelange (Luxembourg)",
    "Dumbéa (New Caledonia)",
    "Durban (South Africa)",
    "Durrës (Albania)",
    "Dushanbe (Tajikistan)",
    "East Jerusalem (West Bank and Gaza Strip)",
    "Ebaye (Marshall Islands)",
    "Ebebiyin (Equatorial Guinea)",
    "Edinburgh of the Seven Seas (Saint Helena)",
    "Elbasan (Albania)",
    "Encamp (Andorra)",
    "Erdenet (Mongolia)",
    "Esch-sur-Alzette (Luxembourg)",
    "Espargos (Cape Verde)",
    "Espoo (Finland)",
    "Faaa (French Polynesia)",
    "Faisalabad (Pakistan)",
    "Fakaifou Village (Tuvalu)",
    "Fale old settlement (Tokelau)",
    "Fes (Morocco)",
    "Fig Tree (Saint Kitts and Nevis)",
    "Fomboni (Comoros)",
    "Fort-de-France (Martinique)",
    "Franceville (Gabon)",
    "Francistown (Botswana)",
    "Freeport (Bahamas)",
    "Freetown (Sierra Leone)",
    "Funafuti (Tuvalu)",
    "Fuvahmulah (Maldives)",
    "Gaborone (Botswana)",
    "Gabú (Guinea-Bissau)",
    "Ganja (Azerbaijan)",
    "Gaza (West Bank and Gaza Strip)",
    "Gbarnga (Liberia)",
    "Gent (Belgium)",
    "Genève (Switzerland)",
    "George Town (Cayman Islands)",
    "Georgetown (Guyana)",
    "Georgetown (Saint Helena)",
    "Georgetown (Saint Vincent and the Grenadines)",
    "Gibraltar (Gibraltar)",
    "Gisenyi (Rwanda)",
    "Gitega (Burundi)",
    "Giza (Egypt)",
    "Gonder (Ethiopia)",
    "Gouyave (Grenada)",
    "Graz (Austria)",
    "Grenville (Grenada)",
    "Guatemala City (Guatemala)",
    "Guayaquil (Ecuador)",
    "Gulu (Uganda)",
    "Gyumri (Armenia)",
    "Göteborg (Sweden)",
    "Hafnarfjörður (Iceland)",
    "Half Tree Hollow (Saint Helena)",
    "Hamburg (Germany)",
    "Hamhŭng (Korea, Dem. People's Rep. of)",
    "Hamilton (Bermuda)",
    "Hanoi (Viet Nam)",
    "Harare (Zimbabwe)",
    "Hargeysa (Somalia)",
    "Havana (Cuba)",
    "Helsinki (Finland)",
    "Herceg Novi (Montenegro)",
    "Herāt (Afghanistan)",
    "Himora (Eritrea)",
    "Hithadhoo (Maldives)",
    "Ho Chi Minh City (Viet Nam)",
    "Homs (Syrian Arab Republic)",
    "Homyel' (Belarus)",
    "Hong Kong (Hong Kong, China)",
    "Honiara (Solomon Islands)",
    "Hoyvík (Faeroe Islands)",
    "Hrodna (Belarus)",
    "Huambo (Angola)",
    "Iaşi (Romania)",
    "Ibadan (Nigeria)",
    "Ilulissat (Greenland)",
    "Incheon (Korea, Republic of)",
    "Irbid (Jordan)",
    "Isfahan (Iran, Islamic Rep. of)",
    "Isfara (Tajikistan)",
    "Istanbul (Turkey)",
    "Istaravshan (Tajikistan)",
    "Iztapalapa (Mexico)",
    "Jakarta (Indonesia)",
    "Jalal-Abad (Kyrgyzstan)",
    "Jeddah (Saudi Arabia)",
    "Jerusalem (Israel)",
    "Jijiga (Ethiopia)",
    "Johannesburg (South Africa)",
    "Juan Díaz (Panama)",
    "Juba (South Sudan, The Republic of)",
    "Jurong Town (Singapore)",
    "Kabul (Afghanistan)",
    "Kakamega (Kenya)",
    "Kampala (Uganda)",
    "Kano (Nigeria)",
    "Kaohsiung (Taiwan, China)",
    "Kara (Togo)",
    "Karachi (Pakistan)",
    "Kathmandu (Nepal)",
    "Kaunas (Lithuania)",
    "Kenema (Sierra Leone)",
    "Keren (Eritrea)",
    "Kharkiv (Ukraine)",
    "Khartoum (Sudan, The Republic of)",
    "Khulna (Bangladesh)",
    "Khān Yūnis (West Bank and Gaza Strip)",
    "Kiffa (Mauritania)",
    "Kigali (Rwanda)",
    "Kingston (Jamaica)",
    "Kingston (Norfolk Island)",
    "Kingstown (Saint Vincent and the Grenadines)",
    "Kinshasa (Congo, Democratic Republic of the)",
    "Kitwe (Zambia)",
    "Klaipėda (Lithuania)",
    "Klaksvík (Faeroe Islands)",
    "Klang (Malaysia)",
    "Kloulklubed (Palau)",
    "Koror (Palau)",
    "Koror Town (Palau)",
    "Koudougou (Burkina Faso)",
    "Koutiala (Mali)",
    "Kowloon (Hong Kong, China)",
    "Košice (Slovakia)",
    "Kraków (Poland)",
    "Kranj (Slovenia)",
    "Kuala Belait (Brunei Darussalam)",
    "Kuala Lumpur (Malaysia)",
    "Kumanovo (Macedonia, The former Yugoslav Rep. of)",
    "Kumasi (Ghana)",
    "Kutaisi (Georgia)",
    "Kyiv (Ukraine)",
    "Kópavogur (Iceland)",
    "La Ceiba (Honduras)",
    "La Condamine (Monaco)",
    "La Paz (Bolivia)",
    "Laayoune (Western Sahara)",
    "Lae (Papua New Guinea)",
    "Lagos (Nigeria)",
    "Lahore (Pakistan)",
    "Lapaha (Tonga)",
    "Larnaca (Cyprus)",
    "Lautoka (Fiji)",
    "Le Gosier (Guadeloupe)",
    "Le Hocq (Jersey)",
    "Le Lamentin (Martinique)",
    "Le Robert (Martinique)",
    "Leava (Wallis and Futuna Islands)",
    "Lelydorp (Suriname)",
    "Leone (American Samoa)",
    "Les Abymes (Guadeloupe)",
    "León (Nicaragua)",
    "Libreville (Gabon)",
    "Liepāja (Latvia)",
    "Lilongwe (Malawi)",
    "Lima (Peru)",
    "Limassol (Cyprus)",
    "Limón (Costa Rica)",
    "Linden (Guyana)",
    "Linz (Austria)",
    "Lira (Uganda)",
    "Lisbon (Portugal)",
    "Liverpool (United Kingdom)",
    "Ljubljana (Slovenia)",
    "Lomé (Togo)",
    "London (United Kingdom)",
    "Los Angeles (United States)",
    "Luanda (Angola)",
    "Lubango (Angola)",
    "Lubumbashi (Congo, Democratic Republic of the)",
    "Lucaya (Bahamas)",
    "Luganville (Vanuatu)",
    "Lusaka (Zambia)",
    "Luxembourg (Luxembourg)",
    "Lyon (France)",
    "Macau (Macau, China)",
    "Madrid (Spain)",
    "Maharagama (Sri Lanka)",
    "Majuro (Marshall Islands)",
    "Malabo (Equatorial Guinea)",
    "Malango (Solomon Islands)",
    "Male (Maldives)",
    "Maliana (Timor-Leste)",
    "Malmö (Sweden)",
    "Managua (Nicaragua)",
    "Manama (Bahrain)",
    "Mandalay (Myanmar)",
    "Manila (Philippines)",
    "Manzini (Swaziland)",
    "Maputo (Mozambique)",
    "Maputsoe (Lesotho)",
    "Maracaibo (Venezuela, Bolivarian Rep. of)",
    "Maracay (Venezuela, Bolivarian Rep. of)",
    "Maradi (Niger)",
    "Maribor (Slovenia)",
    "Marigot (Dominica)",
    "Market Shop (Saint Kitts and Nevis)",
    "Marseille (France)",
    "Masaya (Nicaragua)",
    "Maseru (Lesotho)",
    "Mashhad (Iran, Islamic Rep. of)",
    "Mata-Utu (Wallis and Futuna Islands)",
    "Matola (Mozambique)",
    "Matoury (French Guiana)",
    "Mazār-e Sharīf (Afghanistan)",
    "Mbabane (Swaziland)",
    "Mbuji-Mayi (Congo, Democratic Republic of the)",
    "Mecca (Saudi Arabia)",
    "Medellín (Colombia)",
    "Melbourne (Australia)",
    "Menen (Nauru)",
    "Mexico City (Mexico)",
    "Milan (Italy)",
    "Mindelo (Cape Verde)",
    "Minsk (Belarus)",
    "Miquelon (Saint Pierre and Miquelon)",
    "Misratah (Libyan Arab Jamahiriya)",
    "Mixco (Guatemala)",
    "Mogadishu (Somalia)",
    "Mogoditshane (Botswana)",
    "Mohale's Hoek (Lesotho)",
    "Mombasa (Kenya)",
    "Mon Repos (Trinidad and Tobago)",
    "Monaco (Monaco)",
    "Monrovia (Liberia)",
    "Mont-Dore (New Caledonia)",
    "Monte-Carlo (Monaco)",
    "Montevideo (Uruguay)",
    "Montréal (Canada)",
    "Moroni (Comoros)",
    "Moscow (Russian Federation)",
    "Mosta (Malta)",
    "Moundou (Chad)",
    "Moutsamoudou (Comoros)",
    "Mueang Nonthaburi (Thailand)",
    "Mulifanua (Samoa)",
    "Mumbai (India)",
    "Munich (Germany)",
    "Muscat (Oman)",
    "Mwanza (Tanzania, United Republic of)",
    "Mzuzu (Malawi)",
    "N'Djamena (Chad)",
    "Nairobi (Kenya)",
    "Namangan (Uzbekistan)",
    "Nampula (Mozambique)",
    "Namp’o (Korea, Dem. People's Rep. of)",
    "Naples (Italy)",
    "Narva (Estonia)",
    "Nasinu (Fiji)",
    "Nassau (Bahamas)",
    "Nay Pyi Taw (Myanmar)",
    "Ndola (Zambia)",
    "Neiafu (Tonga)",
    "New Amsterdam (Guyana)",
    "New Kingston (Jamaica)",
    "New York City (United States)",
    "Ngozi (Burundi)",
    "Niamey (Niger)",
    "Nicosia (Cyprus)",
    "Nikšić (Montenegro)",
    "Nitra (Slovakia)",
    "Niš (Serbia)",
    "Norsup (Vanuatu)",
    "Nouadhibou (Mauritania)",
    "Nouakchott (Mauritania)",
    "Nouméa (New Caledonia)",
    "Novi Sad (Serbia)",
    "Novosibirsk (Russian Federation)",
    "Nukunonu (Tokelau)",
    "Nuku‘alofa (Tonga)",
    "Nuuk (Greenland)",
    "Nyala (Sudan, The Republic of)",
    "Nzérékoré (Guinea)",
    "Odense (Denmark)",
    "Odesa (Ukraine)",
    "Oistins (Barbados)",
    "Omdurman (Sudan, The Republic of)",
    "Oran (Algeria)",
    "Oranjestad (Aruba)",
    "Osaka (Japan)",
    "Osh (Kyrgyzstan)",
    "Oslo (Norway)",
    "Ostrava (Czech Republic)",
    "Ouagadougou (Burkina Faso)",
    "Pago Pago (American Samoa)",
    "Pakse (Lao People's Dem. Rep.)",
    "Panamá (Panama)",
    "Pantufo (Sao Tome and Principe)",
    "Papeete (French Polynesia)",
    "Paramaribo (Suriname)",
    "Paris (France)",
    "Paysandú (Uruguay)",
    "Peel (Isle of Man)",
    "Perseverance (Seychelles)",
    "Petaling Jaya (Malaysia)",
    "Phnom Penh (Cambodia)",
    "Phuntsholing (Bhutan)",
    "Piggotts (Antigua and Barbuda)",
    "Pikine (Senegal)",
    "Plovdiv (Bulgaria)",
    "Plymouth (Montserrat)",
    "Podgorica (Montenegro)",
    "Pointe-Noire (Congo)",
    "Port Louis (Mauritius)",
    "Port Moresby (Papua New Guinea)",
    "Port-Gentil (Gabon)",
    "Port-Vila (Vanuatu)",
    "Port-au-Prince (Haiti)",
    "Porto (Portugal)",
    "Porto-Novo (Benin)",
    "Portsmouth (Dominica)",
    "Prague (Czech Republic)",
    "Praia (Cape Verde)",
    "Prilep (Macedonia, The former Yugoslav Rep. of)",
    "Puente Alto (Chile)",
    "Punaauia (French Polynesia)",
    "Pyongyang (Korea, Dem. People's Rep. of)",
    "Pátra (Greece)",
    "Pātan (Nepal)",
    "Quezon City (Philippines)",
    "Quito (Ecuador)",
    "Rabat (Morocco)",
    "Ramsey (Isle of Man)",
    "Ra’s Bayrūt (Lebanon)",
    "Reykjavík (Iceland)",
    "Riga (Latvia)",
    "Rijeka (Croatia)",
    "Rio de Janeiro (Brazil)",
    "Riyadh (Saudi Arabia)",
    "Road Town (British Virgin Islands)",
    "Rome (Italy)",
    "Rosario (Argentina)",
    "Roseau (Dominica)",
    "Rotterdam (Netherlands)",
    "Rundu (Namibia)",
    "Saint Croix (Virgin Islands (US))",
    "Saint George (Bermuda)",
    "Saint George's (Grenada)",
    "Saint Helier (Jersey)",
    "Saint John (Jersey)",
    "Saint John’s (Antigua and Barbuda)",
    "Saint Peter Port (Guernsey)",
    "Saint Peters (Montserrat)",
    "Saint Petersburg (Russian Federation)",
    "Saint Sampson (Guernsey)",
    "Saint-Denis (Réunion)",
    "Saint-Laurent-du-Maroni (French Guiana)",
    "Saint-Paul (Réunion)",
    "Saint-Pierre (Réunion)",
    "Saint-Pierre (Saint Pierre and Miquelon)",
    "Saipan (Northern Mariana Islands)",
    "Salto (Uruguay)",
    "Samarkand (Uzbekistan)",
    "Samut Prakan (Thailand)",
    "San Fernando (Trinidad and Tobago)",
    "San Francisco (Costa Rica)",
    "San Ignacio (Belize)",
    "San Jose Village (Northern Mariana Islands)",
    "San José (Costa Rica)",
    "San Juan (Puerto Rico)",
    "San Lorenzo (Paraguay)",
    "San Marino (San Marino)",
    "San Miguel (El Salvador)",
    "San Miguelito (Panama)",
    "San Nicolas (Aruba)",
    "San Pawl il-Baħar (Malta)",
    "San Pedro (Belize)",
    "San Pedro Sula (Honduras)",
    "San Salvador (El Salvador)",
    "Sanaa (Yemen)",
    "Sandy Ground Village (Anguilla)",
    "Santa Cruz de la Sierra (Bolivia)",
    "Santiago (Chile)",
    "Santiago de Cuba (Cuba)",
    "Santiago de los Caballeros (Dominican Republic)",
    "Santo Domingo (Dominican Republic)",
    "Santo Domingo Oeste (Dominican Republic)",
    "Sarajevo (Bosnia and Herzegovina)",
    "Savannakhet (Lao People's Dem. Rep.)",
    "Schaan (Liechtenstein)",
    "Sector 3 (Romania)",
    "Seeb (Oman)",
    "Seoul (Korea, Republic of)",
    "Serekunda (Gambia)",
    "Seria (Brunei Darussalam)",
    "Serravalle (San Marino)",
    "Sfax (Tunisia)",
    "Shanghai (China)",
    "Sharjah (United Arab Emirates)",
    "Shenzhen (China)",
    "Shymkent (Kazakhstan)",
    "Siem Reap (Cambodia)",
    "Sikasso (Mali)",
    "Singapore (Singapore)",
    "Sisimiut (Greenland)",
    "Skopje (Macedonia, The former Yugoslav Rep. of)",
    "Sofia (Bulgaria)",
    "Sokodé (Togo)",
    "Sousse (Tunisia)",
    "South Dublin (Ireland)",
    "Soyapango (El Salvador)",
    "Spanish Town (Jamaica)",
    "Speightstown (Barbados)",
    "Split (Croatia)",
    "Stanley (Falkland Islands (Malvinas))",
    "Stockholm (Sweden)",
    "Suai (Timor-Leste)",
    "Sumqayıt (Azerbaijan)",
    "Surabaya (Indonesia)",
    "Suva (Fiji)",
    "Sydney (Australia)",
    "Szeged (Hungary)",
    "São Paulo (Brazil)",
    "São Tomé (Sao Tome and Principe)",
    "Taichung (Taiwan, China)",
    "Taipa (Macau, China)",
    "Taipei (Taiwan, China)",
    "Takeo (Cambodia)",
    "Tallinn (Estonia)",
    "Tamale (Ghana)",
    "Tampere (Finland)",
    "Tamuning (Guam)",
    "Tanki Leendert (Aruba)",
    "Tarawa (Kiribati)",
    "Tartu (Estonia)",
    "Tashkent (Uzbekistan)",
    "Tbilisi (Georgia)",
    "Tegucigalpa (Honduras)",
    "Tehran (Iran, Islamic Rep. of)",
    "Tel Aviv (Israel)",
    "The Hague (Netherlands)",
    "The Valley (Anguilla)",
    "Thessaloníki (Greece)",
    "Thimphu (Bhutan)",
    "Tijuana (Mexico)",
    "Tirana (Albania)",
    "Tiraspol (Moldova, Republic of)",
    "Toamasina (Madagascar)",
    "Tokyo (Japan)",
    "Toronto (Canada)",
    "Touba (Senegal)",
    "Triesen (Liechtenstein)",
    "Tripoli (Lebanon)",
    "Tripoli (Libyan Arab Jamahiriya)",
    "Trondheim (Norway)",
    "Tsirang (Bhutan)",
    "Tunis (Tunisia)",
    "Tórshavn (Faeroe Islands)",
    "Türkmenabat (Turkmenistan)",
    "Tāfuna (American Samoa)",
    "Ulan Bator (Mongolia)",
    "Umm Şalāl Muḩammad (Qatar)",
    "Vacoas (Mauritius)",
    "Vaduz (Liechtenstein)",
    "Valencia (Spain)",
    "Vanadzor (Armenia)",
    "Varna (Bulgaria)",
    "Victoria (Hong Kong, China)",
    "Victoria (Seychelles)",
    "Vienna (Austria)",
    "Vientiane (Lao People's Dem. Rep.)",
    "Vieux Fort (Saint Lucia)",
    "Villa Nueva (Guatemala)",
    "Vilnius (Lithuania)",
    "Walvis Bay (Namibia)",
    "Warsaw (Poland)",
    "Wellington (New Zealand)",
    "West Bay (Cayman Islands)",
    "West Jerusalem (Israel)",
    "Windhoek (Namibia)",
    "Winejok (South Sudan, The Republic of)",
    "Woodlands (Singapore)",
    "Yangon (Myanmar)",
    "Yaoundé (Cameroon)",
    "Yei (South Sudan, The Republic of)",
    "Yerevan (Armenia)",
    "Yigo Village (Guam)",
    "Yokohama (Japan)",
    "Zagreb (Croatia)",
    "Zarqa (Jordan)",
    "Zenica (Bosnia and Herzegovina)",
    "Zinder (Niger)",
    "Zürich (Switzerland)",
    "les Escaldes (Andorra)",
    "Århus (Denmark)",
    "Łódź (Poland)",
    "Ḩawallī (Kuwait)",
  ];
  List<String> predefinedCountries = Countries.list.map((c) => c.name).toList();
  List<String> predefinedInterests = [
    "Acting",
    "Action games",
    "Action movies",
    "Adventure travel",
    "Advertising",
    "Agriculture",
    "Air travel",
    "American football",
    "Animated movies",
    "Anime movies",
    "Architecture",
    "Association football (Soccer)",
    "Audio equipment",
    "Automobiles",
    "Auto racing",
    "Aviation",
    "Baking",
    "Ballet",
    "Banking",
    "Barbecue",
    "Bars",
    "Baseball",
    "Basketball",
    "Beaches",
    "Beauty salons",
    "Beer",
    "Birds",
    "Blues music",
    "Board games",
    "Boating",
    "Boats",
    "Bodybuilding",
    "Bollywood movies",
    "Books",
    "Boutiques",
    "Browser games",
    "Business",
    "Camcorders",
    "Cameras",
    "Camping",
    "Card games",
    "Car rentals",
    "Casino games",
    "Cats",
    "Charity and causes",
    "Children’s clothing",
    "Chinese cuisine",
    "Chocolate",
    "Classical music",
    "Coffee",
    "Coffeehouses",
    "College football",
    "Comedy movies",
    "Comics",
    "Community issues",
    "Computer memory",
    "Computer monitors",
    "Computer processors",
    "Computer servers",
    "Concerts",
    "Construction",
    "Cosmetics",
    "Country music",
    "Coupons",
    "Crafts",
    "Creditcards",
    "Cruises",
    "Dance",
    "Dancehalls",
    "Dance music",
    "Dating",
    "Design",
    "Desktop computers",
    "Desserts",
    "Digital marketing",
    "Diners",
    "Discount stores",
    "Display advertising",
    "Distilled beverage",
    "Documentary movies",
    "Dogs",
    "Do it yourself (DIY)",
    "Drama movies",
    "Drawing",
    "Dresses",
    "Drums",
    "E-book readers",
    "E-books",
    "Economics",
    "Ecotourism",
    "Electric vehicle",
    "Electronic music",
    "Email marketing",
    "Energy drinks",
    "Engineering",
    "Entrepreneurship",
    "Environmentalism",
    "Family",
    "Fantasy movies",
    "Fashion design",
    "Fast casual restaurants",
    "Fast food",
    "Fast food restaurants",
    "Fatherhood",
    "Fiction books",
    "Fine art",
    "First-person shooter games",
    "Fish",
    "Fishing",
    "Fragrances",
    "Free software",
    "French cuisine",
    "Friendship",
    "Furniture",
    "Gambling",
    "Game consoles",
    "Gardening",
    "German cuisine",
    "Golf",
    "Gospel music",
    "GPS devices",
    "Graphic design",
    "Greek cuisine",
    "Guitar",
    "Hair products",
    "Handbags",
    "Hard drives",
    "Health care",
    "Heavy metal music",
    "Higher education",
    "Hip hop music",
    "Home Appliances",
    "Home improvement",
    "Horror movies",
    "Horseback riding",
    "Horses",
    "Hotels",
    "Hunting",
    "Hybrids",
    "Indian cuisine",
    "Insurance",
    "Interior design",
    "Investment",
    "Investment banking",
    "Investment banking",
    "Italian cuisine",
    "Japanese cuisine",
    "Jazz music",
    "Jewelry",
    "Juice",
    "Korean cuisine",
    "Lakes",
    "Latin American cuisine",
    "Law",
    "Literature",
    "Luxury goods",
    "Magazines",
    "Management",
    "Manga",
    "Marathons",
    "Marketing",
    "Marriage",
    "Massively multiplayer online games",
    "Massively multiplayer online role-playing games",
    "Meditation",
    "Men’s clothing",
    "Mexican cuisine",
    "Middle Eastern cuisine",
    "Military",
    "Minivans",
    "Mobile phones",
    "Mortgage loans",
    "Motherhood",
    "Motorcycles",
    "Mountain biking",
    "Mountains",
    "Musical theatre",
    "Music festivals",
    "Music videos",
    "Mystery fiction",
    "Nature",
    "Network storage",
    "Newspapers",
    "Nightclubs",
    "Non-fiction books",
    "Nursing",
    "Online",
    "Online advertising",
    "Online banking",
    "Online banking",
    "Online games",
    "Online poker",
    "Online shopping",
    "Organic food",
    "Painting",
    "Parenting",
    "Parties",
    "Performing arts",
    "Personal finance",
    "Pet food",
    "Photography",
    "Physical exercise",
    "Physical fitness",
    "Pizza",
    "Plays",
    "Politics",
    "Pop music",
    "Portable media players",
    "Projectors",
    "Puzzle video games",
    "Rabbits",
    "Racing games",
    "Real estate",
    "Recipes",
    "Religion",
    "Reptiles",
    "Retail",
    "Retail banking",
    "Retail banking",
    "Rhythm and blues music",
    "Rock musicSoul music",
    "Role-playing games",
    "Romance novels",
    "Running",
    "RVs",
    "Sales",
    "Science",
    "Science fiction movies",
    "Scooters",
    "Sculpture",
    "Seafood",
    "Search engine optimization",
    "Shoes",
    "Shooter games",
    "Shopping malls",
    "Simulation games",
    "Singing",
    "Skiing",
    "Small business",
    "Smartphones",
    "Snowboarding",
    "Social media",
    "Social media marketing",
    "Soft drinks",
    "Software",
    "Spanish cuisine",
    "Spas",
    "Sports games",
    "Strategy games",
    "Sunglasses",
    "Surfing",
    "Sustainability",
    "SUVs",
    "Swimming",
    "Tablet computers",
    "Tattoos",
    "Tea",
    "Televisions",
    "Tennis",
    "Thai cuisine",
    "Theatre",
    "Theme parks",
    "Thriathlons",
    "Thriller movies",
    "Tourism",
    "Trucks",
    "TV comedies",
    "TV game shows",
    "TV reality shows",
    "TV talkshows",
    "Vacations",
    "Veganism",
    "Vegetarianism",
    "Veterans",
    "Video games",
    "Vietnamese cuisine",
    "Volleyball",
    "Volunteering",
    "Web design",
    "Web development",
    "Web hosting",
    "Weddings",
    "Weight training",
    "Wine",
    "Women’s clothing",
    "Word games",
    "Writing",
    "Yoga",
  ];

  NewsSettings(
      {required this.cities,
      required this.countries,
      required this.interests,
      required this.wantsCities,
      required this.wantsCountries,
      required this.wantsInterests,
      required this.locale,
      required this.userPrompt});

  factory NewsSettings.defaults() {
    return NewsSettings(
      cities: [],
      countries: [],
      interests: [],
      wantsCities: false,
      wantsCountries: false,
      wantsInterests: false,
      locale: 'en',
      userPrompt: '',
    );
  }
}
